### ISSUE TITLE
[ Time and Date ] Unable to set timezone

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#12]
When setting timezone during first boot and in settings doesnt work

**Comment by joelselvaraj** [comment]
Temporary fix is to run `sudo dpkg-reconfigure tzdata` and select the timezone from command line options presented. Then open the settings->time and date. The time should now be updated.
Related to https://gitlab.com/ubports/community-ports/pinephone/-/issues/6 I guess.

**Comment by geeky-neo** [comment]
ln: failed to create symbolic link '/etc/localtime.dpkg-new': Read-only file system

Current default time zone: 'Asia/Kolkata'
Local time is now:      Wed May  6 09:25:50 UTC 2020.
Universal Time is now:  Wed May  6 09:25:50 UTC 2020.

debconf: DbDriver "config": could not write /var/cache/debconf/config.dat-new: Read-only file system
phablet@ubuntu-phablet:~$

**Comment by joelselvaraj** [comment]
Run `sudo mount -o remount,rw /` first and then run the command

**Comment by joelselvaraj** [comment]
Fixed in the latest GSI
