### ISSUE TITLE
[ Fingerprint ] Not working

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#14]
Fingerprint not working

**Comment by joelselvaraj** [comment]
Will come once halium has support for it. Almost none of the community devices have fingerprint working right now. We need to build a libbiometryd plugin for it. But I think people are working for generic one for trebble supported devices. So once it ready in halium-9 we can work on that. Till that we have to wait

**Comment by joelselvaraj** [comment]
With Erfan's v6 test build, fingerprint works! https://build.lolinet.com/file/halium/GSI/.ubports_GSI_installer_v6_TEST_2002.zip. Once it gets to main GSI version, this issue can be closed.

**Comment by joelselvaraj** [comment]
Can be tracked in #20. Will update there once stable version released. Closing here.
