### ISSUE TITLE
PulseAudio

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#17]
cat pulseaudio-trust-stored.log

Failed to register agent for user: org.freedesktop.DBus.Error.ServiceUnknown: The name core.trust.dbus.Agent.PulseAudio was not provided by any .service files

**Comment by joelselvaraj** [comment]
As of now, there is no specific issue regarding pulseaudio. The issues are related to Audio drivers and firmware. we ll track them separately.
