### ISSUE TITLE
[ Display ] Screen not switching off after idle timeout of 5 minutes.

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#18]
Phone battery had drained, hooked in the charger, and after 10 minutes, switched it on.
Screen not switching off after idle timeout of 5 minutes although it was working earlier.
[dmesg.txt](https://github.com/ubports-beryllium/projectmanagement/files/4598350/dmesg.txt)
[logcat.txt](https://github.com/ubports-beryllium/projectmanagement/files/4598352/logcat.txt)

**Comment by geeky-neo** [comment]
Crash seen in logcat file.

**Comment by joelselvaraj** [comment]
In the latest GSI, this is fixed. Switches off both on battery and while charging.
