### ISSUE TITLE
ErfanGSIv5 : Error logs on launching/operating Camera App

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#19]
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Creating a QMirClientScreen now
Import path added "/opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/lib/aarch64-linux-gnu"
Camera app directory "/opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3"
QFSFileEngine::map: Mapping a file beyond its size is not portable

(camera-app:27536): GLib-GObject-WARNING **: g_object_class_override_property: Can't find property to override for 'GstDroidCamSrc::exposure-mode'
ALSA lib conf.c:3814:(snd_config_update_r) cannot access file /usr/share/alsa/alsa.conf
qq= QDeclarativeCamera_QML_31(0x27a42360) 0x27bd94f0
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.168\" (uid=32011 pid=27536 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4747 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.168\" (uid=32011 pid=27536 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4747 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.168\" (uid=32011 pid=27536 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4747 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.168\" (uid=32011 pid=27536 comm=\"./camera-app \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4747 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
Failed to register user metric: "camera-videos" " "<b>%1</b> videos recorded today" ":  Launch helper exited with unknown return code 1
Failed to register user metric: "camera-photos" " "<b>%1</b> photos taken today" ":  Launch helper exited with unknown return code 1
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
void LocalSensorManagerInterface::loadPluginFinished(QDBusPendingCallWatcher*) "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.186\" (uid=32011 pid=27536 comm=\"./camera-app \") interface=\"local.SensorManager\" member=\"loadPlugin\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.nokia.SensorService\" (uid=0 pid=1941 comm=\"/usr/sbin/sensorfwd --config-file=/etc/device-info\")"
qml: updateViewfinderResolution: viewfinder resolutions is not known yet.
qml: updateViewfinderResolution: viewfinder resolutions is not known yet.

(camera-app:27536): GStreamer-CRITICAL **: gst_caps_is_equal: assertion 'GST_IS_CAPS (caps1)' failed

(camera-app:27536): GLib-GObject-WARNING **: g_object_set_valist: object class 'GstDroidCamSrc' has no property named 'preview-filter'

(camera-app:27536): GLib-GObject-WARNING **: g_object_set_valist: object class 'GstDroidCamSrc' has no property named 'preview-filter'
[PERFORMANCE]: Last frame took 102 ms to render.
qq= ResponsiveGridView_QMLTYPE_125_QML_130(0x280c85a0) 0x280cac30
QFileSystemWatcher::removePaths: list is empty
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/MediaInfoPopover.qml:30:5: QML Item: Binding loop detected for property "height"
file:///usr/lib/aarch64-linux-gnu/qt5/qml/Ubuntu/Components/Popups/1.3/Popover.qml:250:9: QML Item: Binding loop detected for property "height"
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/GalleryView.qml:104:5: QML OrientationHelper: All the parents must have an id.
State saving disabled for PhotogridView-photogridView:QQuickPinchArea-galleryViewPinch:_opt_click.ubuntu.com_com.ubuntu.camera_3.1.2+gstdroid3_PhotogridView.qml:139:9:gridView, class OrientationHelper
qml: updateViewfinderResolution: viewfinder resolutions is not known yet.
Unable to open the camera "primary" for read to query the parameter info: "No such file or directory"
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/SlideshowView.qml:422: TypeError: Cannot read property 'actions' of null
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/OptionButton.qml:24:39: Unable to assign [undefined] to QString
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/OptionButton.qml:33: TypeError: Cannot read property 'value' of undefined
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/OptionButton.qml:24:39: Unable to assign [undefined] to QString
qml: updateViewfinderResolution: For target resolution 4032x3024, select 1920x1440 for viewfinder resolution.
qml: updateViewfinderResolution: For target resolution 4032x3024, select 1920x1440 for viewfinder resolution.
Unable to open the camera "primary" for read to query the parameter info: "No such file or directory"

(camera-app:27536): GStreamer-CRITICAL **: gst_caps_is_equal: assertion 'GST_IS_CAPS (caps1)' failed
qml: updateViewfinderResolution: For target resolution 4032x3024, select 1920x1440 for viewfinder resolution.
qml: Flipped
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(599,1285) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(624,1281) id:2000002 timeHeld:0)

(camera-app:27536): GStreamer-CRITICAL **: gst_util_fraction_to_double: assertion 'src_d != 0' failed
qml: Picture saved as /home/phablet/Pictures/com.ubuntu.camera/IMG_00000004.jpg
Failed to vibrate with pattern: "The name com.lomiri.hfd was not provided by any .service files"
qml: Flipped
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/MediaInfoPopover.qml:11: TypeError: Cannot read property 'url' of null
[PERFORMANCE]: Last frame took 37 ms to render.
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000001.mov (270,270): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000002.mov (270,270): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000003.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000001.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000002.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000003.mov (270,270): FAILED PREVIOUSLY
[PERFORMANCE]: Last frame took 77 ms to render.
[PERFORMANCE]: Last frame took 101 ms to render.
qml: Flipped
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000001.mov (562,562): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000003.mov (562,562): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000002.mov (562,562): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000003.mov (270,270): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000001.mov (270,270): FAILED PREVIOUSLY
Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000002.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000003.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000001.mov (270,270): FAILED PREVIOUSLY
file:///opt/click.ubuntu.com/com.ubuntu.camera/3.1.2+gstdroid3/PhotogridView.qml:181:17: QML Image: Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::checkFinished(): no artwork for thumbnail: /home/phablet/Videos/com.ubuntu.camera/clip_00000002.mov (270,270): FAILED PREVIOUSLY

**Comment by geeky-neo** [comment]
https://pastebin.com/fihUWZm8

**Comment by joelselvaraj** [comment]
We will track video recording failure in #16. Closing here.
