### ISSUE TITLE
Cellular Data Support(LTE)

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#2]
Cellular Data Support(LTE)

- [ ] Connect to cellular data service

- [ ] Connect to cellular data service while roaming.

- [ ] Stock network speed between the phone and access point.

**Comment by joelselvaraj** [comment]
Requires halium guys to fix this. Its not working in halium-9 for any devices

**Comment by joelselvaraj** [comment]
Tracked in #20. Closing here.
