### ISSUE TITLE
WiFi Support

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#3]
WiFi Support
   

- [x] Connect to WiFi network

- [x]  Auto-Connect to previously connected/remembered WiFi network

- [x] Stock network speed between the phone and access point.

**Comment by joelselvaraj** [comment]
All seems to be working in the new kernel release. Hotspot got created and i was able to connect to. But of-course since cellular data is not working, i wasnt able to test internet connection. But I was able to SSH over wifi. So its good as working.

**Comment by geeky-neo** [comment]
did you check the internet speed over WiFi ?

**Comment by joelselvaraj** [comment]
Oh yes. Just now did. I have a 200Mbps wifi. And i got full speed.

**Comment by geeky-neo** [comment]
Working as expected and speed-test is successful too with correct speed.

**Comment by joelselvaraj** [comment]
Good to know!
