### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#4]
Bluetooth Support

- [x] Routing music via bluetooth

- [ ] Routing call audio via bluetooth.

**Comment by joelselvaraj** [comment]
Music over bluetooth works. But audio routing in call is broken

**Comment by joelselvaraj** [comment]
Bluetooth connections are still buggy. Sometimes it doesnt get paired properly. Needs debuggging

**Comment by geeky-neo** [comment]
Bluetooth gets switched off with GSIv5 + halium-boot.img.

[dmesg.txt](https://github.com/ubports-beryllium/projectmanagement/files/4591101/dmesg.txt)
[logcat.txt](https://github.com/ubports-beryllium/projectmanagement/files/4591102/logcat.txt)

**Comment by geeky-neo** [comment]
1) Bluetooth Auto connect not working.
2) Audio of already running video not routed via Bluetooth on reconnect

**Comment by joelselvaraj** [comment]
Tracked in #20. Closing here.
