### ISSUE TITLE
VPN Support

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#6]
VPN Support

- [ ] Manual Configuration

- [ ] Import from file

**Comment by joelselvaraj** [comment]
Follow this guide: 
https://ubports.com/blog/ubports-blog-1/post/using-vpn-in-ubuntu-touch-132 

It should work. If not, let me know.

**Comment by joelselvaraj** [comment]
Import file feature need to be added by Ubuntu Touch. We cant do anything.

**Comment by joelselvaraj** [comment]
Tracked in #20. Closing here.
