### ISSUE TITLE
Phone Audio

### ISSUE THREAD

**Issue by geeky-neo** [ubports-beryllium/projectmanagement#9]
Phone Audio

- [x] Speaker working for media audio and ringtone

- [ ] Heaphones working for audio and calls

**Comment by joelselvaraj** [comment]
Speaker audio is fixed in https://github.com/ubports-beryllium/android_kernel_xiaomi_sdm845/commit/38c484b57c93464fc996d44695f5d3e7e7ddc863.

**Comment by joelselvaraj** [comment]
Tracked in #20. Closing here.
